### ISSUE TITLE
Devshop Needs Lando

### ISSUE THREAD

**Issue by matthandus** [matthandus/devshop#16]
Imagine a world where Drupal developers can develop in Lando and run a local version of OpenDevShop to act as a personal pipeline to allow them to git ignore the build directories but commit fully built code for deployment to Acquia git repos.

**Comment by matthandus** [comment]
Got to site install and it failed.

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://opendevshop.lndo.site/install.php?profile=devmaster&locale=en&id=1&op=do StatusText: OK ResponseText: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /app/devmaster/modules/devshop/devshop_github/devshop_github.module on line 1573 {"status":true,"percentage":"94","message":"Completed 60 of 64.\u003Cbr \/\u003EInstalled \u003Cem\u003EDevShop Testing\u003C\/em\u003E module."}

Then clicked through to error page and it finished installing.

Boots theme was not enabled as default at first.

**Comment by matthandus** [comment]
- [ ] Install aegir
- [ ] Install drush aliases, where is this handled?
- [ ] Install devmaster into usr folder, is this necessary?
- [ ] Set SSH Key for Devshop
- [ ] Resolve initial site install issues from Drupal Profile
- [ ] Resolve Mysql Geerling Guy Playbook issue, error report below.
- [ ] Resolve Geerling Guy Apache Playbook issue, see error below.
- [ ] Resolve geerlingguy.php  issues, see below.

**Comment by matthandus** [comment]
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
fatal: [devshop.local.computer]: FAILED! => changed=false 
  msg: No package matching 'mysql-server' is available

PLAY RECAP *********************************************************************
devshop.local.computer     : ok=42   changed=12   unreachable=0    failed=1    skipped=13   rescued=0    ignored=1   

ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

**Comment by matthandus** [comment]
TASK [geerlingguy.apache : Enable Apache mods.] ********************************
changed: [devshop.local.computer] => (item=rewrite.load)
failed: [devshop.local.computer] (item=ssl.load) => changed=false 
  ansible_loop_var: item
  gid: 0
  group: root
  item: ssl.load
  mode: '0644'
  msg: refusing to convert from file to symlink for /etc/apache2/mods-enabled/ssl.load
  owner: root
  path: /etc/apache2/mods-enabled/ssl.load
  size: 97
  state: file
  uid: 0

PLAY RECAP *********************************************************************
devshop.local.computer     : ok=37   changed=11   unreachable=0    failed=1    skipped=14   rescued=0    ignored=1   

ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

**Comment by matthandus** [comment]
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [devshop.local.computer]: FAILED! => changed=false 
  cache_update_time: 1656042328
  cache_updated: false
  msg: |-
    '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"      install 'php7.3' 'php7.3-apcu' 'php7.3-cli' 'php7.3-common' 'php7.3-curl' 'php7.3-dev' 'php7.3-fpm' 'php7.3-gd' 'php7.3-imap' 'php7.3-json' 'php7.3-mbstring' 'php7.3-opcache' 'php7.3-sqlite3' 'php7.3-xml' 'php7.3-yaml' -o APT::Install-Recommends=no' failed: E: Package 'php7.3' has no installation candidate
    E: Package 'php7.3-apcu' has no installation candidate
    E: Package 'php7.3-cli' has no installation candidate
    E: Package 'php7.3-common' has no installation candidate
    E: Package 'php7.3-curl' has no installation candidate
    E: Package 'php7.3-dev' has no installation candidate
    E: Package 'php7.3-fpm' has no installation candidate
    E: Package 'php7.3-gd' has no installation candidate
    E: Package 'php7.3-imap' has no installation candidate
    E: Package 'php7.3-json' has no installation candidate
    E: Package 'php7.3-mbstring' has no installation candidate
    E: Package 'php7.3-opcache' has no installation candidate
    E: Package 'php7.3-sqlite3' has no installation candidate
    E: Package 'php7.3-xml' has no installation candidate
    E: Package 'php7.3-yaml' has no installation candidate
  rc: 100
  stderr: |-
    E: Package 'php7.3' has no installation candidate
    E: Package 'php7.3-apcu' has no installation candidate
    E: Package 'php7.3-cli' has no installation candidate
    E: Package 'php7.3-common' has no installation candidate
    E: Package 'php7.3-curl' has no installation candidate
    E: Package 'php7.3-dev' has no installation candidate
    E: Package 'php7.3-fpm' has no installation candidate
    E: Package 'php7.3-gd' has no installation candidate
    E: Package 'php7.3-imap' has no installation candidate
    E: Package 'php7.3-json' has no installation candidate
    E: Package 'php7.3-mbstring' has no installation candidate
    E: Package 'php7.3-opcache' has no installation candidate
    E: Package 'php7.3-sqlite3' has no installation candidate
    E: Package 'php7.3-xml' has no installation candidate
    E: Package 'php7.3-yaml' has no installation candidate
  stderr_lines: <omitted>
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Package php7.3-common is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-cli is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-json is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-opcache is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-dev is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-mbstring is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-xml is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-apcu is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-yaml is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3 is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-fpm is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-curl is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-gd is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-imap is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  
    Package php7.3-sqlite3 is not available, but is referred to by another package.
    This may mean that the package is missing, has been obsoleted, or
    is only available from another source
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
devshop.local.computer     : ok=43   changed=14   unreachable=0    failed=1    skipped=22   rescued=0    ignored=1   

ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

**Comment by matthandus** [comment]
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [devshop.local.computer]: FAILED! => changed=false 
  msg: No package matching 'php7.0-common' is available

PLAY RECAP *********************************************************************
devshop.local.computer     : ok=37   changed=11   unreachable=0    failed=1    skipped=15   rescued=0    ignored=1   

ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

**Comment by matthandus** [comment]
Lando uses Bitnami images for Debian 11. Need to ensure the Playbooks are compatible.

`No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye`

**Comment by matthandus** [comment]
Updated lando file to install ansible roles via build steps so they are compatible with latest Debian image.

```
Starting galaxy role install process
- downloading role 'apache', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/3.3.0.tar.gz
- extracting geerlingguy.apache to /usr/share/devshop/roles/geerlingguy.apache
- geerlingguy.apache (3.3.0) was installed successfully
Starting galaxy role install process
- downloading role 'composer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.9.2.tar.gz
- extracting geerlingguy.composer to /usr/share/devshop/roles/geerlingguy.composer
- geerlingguy.composer (1.9.2) was installed successfully
Starting galaxy role install process
- downloading role 'drush', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drush/archive/3.3.0.tar.gz
- extracting geerlingguy.drush to /usr/share/devshop/roles/geerlingguy.drush
- geerlingguy.drush (3.3.0) was installed successfully
Starting galaxy role install process
- downloading role 'git', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-git/archive/3.0.0.tar.gz
- extracting geerlingguy.git to /usr/share/devshop/roles/geerlingguy.git
- geerlingguy.git (3.0.0) was installed successfully
Starting galaxy role install process
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/3.5.0.tar.gz
- extracting geerlingguy.mysql to /usr/share/devshop/roles/geerlingguy.mysql
- geerlingguy.mysql (3.5.0) was installed successfully
Starting galaxy role install process
- downloading role 'nginx', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/3.1.1.tar.gz
- extracting geerlingguy.nginx to /usr/share/devshop/roles/geerlingguy.nginx
- geerlingguy.nginx (3.1.1) was installed successfully
Starting galaxy role install process
- downloading role 'php', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php/archive/4.8.0.tar.gz
- extracting geerlingguy.php to /usr/share/devshop/roles/geerlingguy.php
- geerlingguy.php (4.8.0) was installed successfully
Starting galaxy role install process
- downloading role 'php-mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-php-mysql/archive/2.1.0.tar.gz
- extracting geerlingguy.php-mysql to /usr/share/devshop/roles/geerlingguy.php-mysql
- geerlingguy.php-mysql (2.1.0) was installed successfully
[WARNING]: - dependency geerlingguy.php (None) from role geerlingguy.php-mysql
differs from already installed version (4.8.0), skipping
Starting galaxy role install process
- extracting ansible-role-aegir-user to /usr/share/devshop/roles/ansible-role-aegir-user
- ansible-role-aegir-user was installed successfully
Starting galaxy role install process
- extracting ansible-role-aegir-apache to /usr/share/devshop/roles/ansible-role-aegir-apache
- ansible-role-aegir-apache was installed successfully
- adding dependency: opendevshop.aegir-user
[WARNING]: - dependency geerlingguy.apache (None) from role ansible-role-aegir-
apache differs from already installed version (3.3.0), skipping
- downloading role 'aegir-user', owned by opendevshop
- downloading role from https://github.com/opendevshop/ansible-role-aegir-user/archive/1.5.0-rc8.tar.gz
- extracting opendevshop.aegir-user to /usr/share/devshop/roles/opendevshop.aegir-user
- opendevshop.aegir-user (1.5.0-rc8) was installed successfully
Starting galaxy role install process
- extracting ansible-role-aegir-nginx to /usr/share/devshop/roles/ansible-role-aegir-nginx
- ansible-role-aegir-nginx was installed successfully
[WARNING]: - dependency opendevshop.aegir-user (None) from role ansible-role-
aegir-nginx differs from already installed version (1.5.0-rc8), skipping
[WARNING]: - dependency geerlingguy.nginx (None) from role ansible-role-aegir-
nginx differs from already installed version (3.1.1), skipping
All settings correct for using Composer
Downloading...

Composer (version 2.2.12) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Changed current directory to /var/www/.composer
hirak/prestissimo is not required in your composer.json and has not been removed
./composer.json has been updated
Running composer update hirak/prestissimo
Loading composer repositories with package information
Package "hirak/prestissimo" listed for update is not locked.
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
Killing devshop_appserver_1 ... 
Killing devshop_appserver_1 ... done
Starting devshop_appserver_1 ... done
Creating devshop_database_1  ... done
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please stand by...
usermod: no changes
usermod: no changes
You are about to DROP all tables in your 'drupal7' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                                                                                                         [ok]
 WD php: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in include_once() (line 1389 of /app/src/DevShop/Control/web/includes/bootstrap.inc).                                                       [warning]
WD php: Error: Call to undefined function d() in devmaster_install() (line 14 of /app/devmaster/devmaster.profile).                                                                                                                                  [error]
WD php: Warning: Cannot modify header information - headers already sent by (output started at /app/src/DevShop/Control/web/sites/all/modules/contrib/hosting/site/hosting_site.form.inc:1) in drupal_send_headers() (line 1501 of                   [warning]
/app/src/DevShop/Control/web/includes/bootstrap.inc).
Error: Call to undefined function d() in devmaster_install() (line 14 of /app/devmaster/devmaster.profile).
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
ERROR ==> Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
```
